name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
          # Don't fail if builds branch doesn't exist
      
      - name: Create builds branch if it doesn't exist
        run: |
          if [ ! -d "builds/.git" ]; then
            echo "builds branch doesn't exist, creating it..."
            mkdir -p builds
            cd builds
            git init
            git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
            git checkout -b builds
            echo "# Built plugins" > README.md
            git add README.md
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git commit -m "Initialize builds branch"
          fi
      
      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0  # do not error if nothing to commit.
          git push --set-upstream origin builds --force
